version: 1.0.{build}
configuration: Release

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/XwaOptEditor" if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 1.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- nuget restore XwaOptEditor\XwaOptEditor.sln

build:
  project: XwaOptEditor\XwaOptEditor.sln
  verbosity: minimal

after_build:
- XwaOptEditor\build-dist.cmd

artifacts:
- path: XwaOptEditor\dist
  name: XwaOptEditor
  type: zip
