image: Visual Studio 2022
version: 1.0.{build}
configuration: Release

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/XwaOptEditor" if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

nuget:
  disable_publish_on_pr: true

before_build:
- nuget restore XwaOptEditor\XwaOptEditor.sln

build:
  project: XwaOptEditor\XwaOptEditor.sln
  verbosity: minimal

after_build:
- XwaOptEditor\build-dist.cmd

artifacts:
- path: XwaOptEditor\dist
  name: XwaOptEditor-$(APPVEYOR_BUILD_VERSION)
  type: zip
